import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavSideBar from '@/components/common/NavSideBar'
import RightSideBar from '@/components/common/RightSideBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Homebuilderla',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={`relative max-w-[1560px] w-full h-full mx-auto ${inter.className}`}>
          <NavSideBar/>
          <div className='ml-44 mr-28 px-5'>{children}</div>
          <RightSideBar/>
        </body>
    </html>
  )
}
