import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import App from '@/components/App'
import { Providers } from '@/store/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Homebuilderla',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={`relative max-w-[1560px] w-full h-full mx-auto ${inter.className}`}>
          <Providers>
           <App>{children}</App>
          </Providers>,
        </body>
    </html>
  )
}
